trigger:
- master
- rel/*
- preview/*

pr:
- master
- rel/*
- preview/*

pool:
  vmImage: vs2017-win2016

steps:
- task: DotNetCoreInstaller@0
  displayName: Install Dot Net Core v2.2.1
  inputs:
    version: '2.2.103'

- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables

- powershell: .\build.ps1 -Target UploadTestCoverage
  displayName: Build 
  env:
    CODECOV_TOKEN: $(CODECOV_TOKEN)
    ArtifactDirectory: $(System.DefaultWorkingDirectory)\artifacts
    
- task: CopyFiles@2
  inputs:
    Contents: 'artifacts/tests/**/*'
    TargetFolder: '$(build.artifactstagingdirectory)\Tests'

- task: PublishBuildArtifacts@1
  displayName: Publish Test Data
  inputs:
    pathToPublish: '$(build.artifactstagingdirectory)\Tests'
    artifactType: container
    artifactName: Tests

- task: PublishCodeCoverageResults@1
  displayName: Publish Coverage Results
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: 'artifacts\tests\TestCoverage.xml'
    reportDirectory: 'artifacts\tests\Report'

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: 'testresults-*.trx' 
    searchFolder: 'artifacts\tests'